In [3]:
import torch

## 2.1 Создание нейронов и полносвязных слоев

2.1.1. Используя операции над матрицами и векторами из библиотеки `torch`, реализовать нейрон с заданными весами `weights` и `bias`. Прогнать вектор `inputs` через нейрон и вывести результат. 

In [198]:
class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
        pass

    def forward(self, inputs):
        return  inputs @ self.weights + self.bias


In [199]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14

model = Neuron(weights, bias)
model.forward(inputs)

tensor(4.8400)

2.1.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой с заданными весами `weights` и `biases`. Прогнать вектор `inputs` через слой и вывести результат. 

In [216]:
class Linear:
    def __init__(self, weights, biases):
        self.weights = weights
        self.bias = bias
        pass

    def forward(self, inputs):
        return  inputs @ self.weights + self.bias

In [217]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]]).T

biases = torch.tensor([3.14, 2.71, 7.2])

model = Linear(weights, bias)
model.forward(inputs)

tensor([4.8400, 0.6000, 6.3300])

2.1.3 Реализовать полносвязный слой из __2.1.2__ таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. Продемонстрировать работу.
Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.


In [218]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]]).T

biases = torch.tensor([3.14, 2.71, 7.2])

class Linear:
    def __init__(self, weights, biases):
        self.weights = weights
        self.bias = bias
        self.batch_size = batch_size
        pass

    def forward(self, inputs):

        return  inputs @ self.weights + self.bias

In [219]:
model = Linear(weights, bias)
model.forward(inputs)

tensor([[ 3.7900,  1.3500,  5.0250],
        [ 6.1400, -1.6700,  2.8400],
        [ 2.0400,  1.1910,  2.6660]])

2.1.4 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения). Прогнать вектор `inputs` через слой и вывести результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [222]:
class Linear:
    def __init__(self, n_features, n_neurons):
        # <создать атрибуты объекта weights и biases>
        self.weigths = torch.randn(n_neurons, n_features)
        self.bias = torch.randn(1, n_neurons)
        pass

    def forward(self, inputs):
        return (inputs @ self.weigths.T) + self.bias

In [223]:
batch_size = 10
model = Linear(8, 5)

model.forward(torch.randn(batch_size, 8))

tensor([[ 0.8451,  4.1715, -6.1264,  1.4300,  4.8745],
        [-3.8998, -2.1810,  2.3266,  0.9622,  1.6327],
        [ 6.2002,  6.4705, -1.7432,  1.7234,  0.4331],
        [-1.4239,  2.9462, -6.0569,  3.6318,  2.2707],
        [ 2.5675, -0.1819,  1.2665,  2.7782, -4.2090],
        [-1.4317,  0.6809, -6.6049,  3.9594, -1.8307],
        [-0.7639,  3.5536, -4.3225,  3.5347, -4.3747],
        [ 4.4241,  4.7017, -3.7339,  0.8405,  3.4267],
        [-0.9689, -1.3606, -5.8626,  3.2166,  1.2044],
        [-3.8502,  4.3972, -6.4820,  2.8970,  4.9286]])

2.1.5 Используя решение из __2.1.4__, создать 2 полносвязных слоя и пропустить матрицу `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выбрать произвольно, количество нейронов во втором слое выбрать так, чтобы результатом прогона являлась матрица (3x7). 

In [151]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])


layer1 = Linear(4, 5)
layer2 = Linear(5, 7)

output1 = layer1.forward(inputs)
layer2.forward(output1)

tensor([[  0.2344,  -1.4417,  12.7644,  -1.3389,   6.9742, -13.6056,  -3.3967],
        [-12.7402, -27.6750,  16.7276,   4.4414,   0.3089,  -2.2857, -30.9894],
        [  9.3282,   5.3249,  -1.0687,  10.6605,  -3.8348, -18.0273,   8.3946]])

## 2.2 Создание функций активации

2.2.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [163]:
class ReLU:
    def forward(self, inputs):
        inputs[inputs < 0] = 0
        return inputs
        pass
    
relu = ReLU()

relu.forward(torch.randn(4, 3))

tensor([[0.0000, 0.4721, 0.3084],
        [0.0000, 0.0000, 0.6242],
        [0.3411, 2.1395, 0.2875],
        [0.0000, 0.0000, 1.0651]])

2.2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров.

In [182]:
class Softmax:
    def forward(self, inputs):
        inputs_exp = inputs.exp()       
        return inputs_exp / inputs_exp.sum(dim=1).unsqueeze(1)
        pass
    
    
softmax = Softmax()

softmax.forward(torch.randn(4, 3))

tensor([[0.6781, 0.2477, 0.0742],
        [0.4904, 0.1846, 0.3250],
        [0.4521, 0.3951, 0.1528],
        [0.4835, 0.1306, 0.3859]])

2.2.3 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [194]:
class ELU:
    def __init__(self, alpha):
        self.alpha = alpha
        pass

    def forward(self, inputs):
        inputs[inputs < 0] = ((inputs.exp() - 1) * self.alpha)[inputs < 0]
        return inputs
        pass

In [196]:
layer = ELU(5)
layer.forward(torch.randn(4, 3))

tensor([[ 1.7600,  1.4339, -0.1450],
        [ 0.8427,  0.3649,  1.4184],
        [-4.5330,  0.6681,  1.9240],
        [-2.0094, -4.0768, -0.9199]])

## 2.3 Создание функции потерь

2.3.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)

Создать полносвязный слой с 1 нейроном, прогнать через него батч `inputs` и посчитать значение MSE, трактуя вектор `y` как вектор правильных ответов.

In [205]:
class MSELoss:
    
    def forward(self, y_pred, y_true):
        return ((y_pred - y_true) ** 2) / y_pred.shape[0]

In [214]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

y = torch.tensor([2, 3, 4])

weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14
model = Neuron(weights, bias)
y_pred = model.forward(inputs)

layer = MSELoss()
layer.forward(y_pred, y)

tensor([1.0680, 3.2865, 1.2805])

2.3.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь Categorical Cross-Entropy:

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

Создать полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустить через функцию активации softmax. Посчитать значение CCE, трактуя вектор `y` как вектор правильных ответов.

In [266]:
class CategoricalCrossentropyLoss:
    def forward(self, y_pred, y_true):
        return - (y_true @ y_pred.log()).sum() 
        pass

In [287]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1., 0, 0])

layer_linear = Linear(4, 3)
layer_softmax = Softmax()
loss = CategoricalCrossentropyLoss()

output1 = layer_linear.forward(inputs)
output2 = layer_softmax.forward(output1)

loss.forward(output2, y)


tensor(7.9919)

2.3.3 Модифицировать 2.3.1, добавив L2-регуляризацию.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/d92ca2429275bfdc0474523babbafe014ca8b580)


In [282]:
class MSELossL2:
    def __init__(self, lambda_, layer):
        self.lambda_ = lambda_
        self.layer = layer
        pass

    def data_loss(self, y_pred, y_true):
        return ((y_pred - y_true) ** 2).sum()
        
        pass

    def reg_loss(self, layer):
        # используйте атрибуты объекта layer, в которых хранятся веса слоя
        return self.lambda_ * layer.weights.sum()
        
        pass

    def forward(self, y_pred, y_true):
        return self.data_loss(y_pred, y_true) + self.reg_loss(self.layer)

In [284]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

y = torch.tensor([2, 3, 4])

weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14
lambda_ = 2

model = Neuron(weights, bias)
y_pred = model.forward(inputs)

layer = MSELossL2(lambda_, model)
layer.forward(y_pred, y)

tensor(17.5053)